[2022-10-10T15:55:58.617+0600] {processor.py:156} INFO - Started process (PID=448) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:55:58.620+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:55:58.622+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:55:58.621+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:55:58.673+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:55:58.667+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:55:58.674+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:55:58.712+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.104 seconds
[2022-10-10T15:56:29.764+0600] {processor.py:156} INFO - Started process (PID=472) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:56:29.765+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:56:29.765+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:29.765+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:56:29.783+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:29.781+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:56:29.783+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:56:29.808+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.047 seconds
[2022-10-10T15:57:01.005+0600] {processor.py:156} INFO - Started process (PID=496) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:57:01.006+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:57:01.006+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:01.006+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:57:01.024+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:01.022+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:57:01.024+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:57:01.047+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.045 seconds
[2022-10-10T15:57:31.861+0600] {processor.py:156} INFO - Started process (PID=520) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:57:31.863+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:57:31.865+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:31.864+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:57:31.894+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:31.892+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:57:31.894+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:57:31.919+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.067 seconds
[2022-10-10T15:58:02.492+0600] {processor.py:156} INFO - Started process (PID=544) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:58:02.495+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:58:02.496+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:02.496+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:58:02.522+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:02.520+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:58:02.523+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:58:02.546+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.063 seconds
[2022-10-10T15:58:33.274+0600] {processor.py:156} INFO - Started process (PID=568) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:58:33.275+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:58:33.276+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:33.275+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:58:33.294+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:33.292+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:58:33.294+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:58:33.318+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.047 seconds
[2022-10-10T15:59:04.220+0600] {processor.py:156} INFO - Started process (PID=592) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:59:04.221+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py for tasks to queue
[2022-10-10T15:59:04.221+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:59:04.221+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:59:04.241+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:59:04.238+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py", line 28, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:59:04.241+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py
[2022-10-10T15:59:04.264+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_mysql_google_bigquery.py took 0.047 seconds
